footprint: [[-0.5, -0.1], [-0.5, 0.1], [0.5, 0.1], [0.5, -0.1]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5
raytrace_range: 5
#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: point_cloud_sensor

    point_cloud_sensor: {sensor_frame: laser, clearing: true, topic: point_Cloud, data_type: PointCloud2, min_obstacle_height: 0.2}

inflation:
    inflation_radius: 0.2 #0.55
